import { yekan } from "@/utils/fonts";
import { Inter } from "next/font/google";
import 'tailwindcss/tailwind.css';
import '../globals.css';
import Providers from "src/redux/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "coffee shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html >
      <body className={yekan.className}>
        
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
